# 共通環境
spring:
  datasource:
    url: jdbc:h2:mem:testdb
  sql:
    init:
      schema-locations:
      - classpath:schema.sql
      data-locations:
      - classpath:data.sql
      mode: always
  h2:
    console:
      enabled: true
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.beit_and_pear.model
  mapper-locations:
  - classpath*:/com/beit_and_pear/mapper/h2/*.xml
  
  
#server:
#  port: 5000
  
---

# 開発環境（dev）
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    url: jdbc:mysql://aa4xwwve15xvvl.cc2cv1hryoxu.ap-northeast-1.rds.amazonaws.com:3306/ebdb
    username: admin
    password: tanaka3284
  sql:
    init:
      mode: always
      