# 共通環境
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.beit_and_pear.model
  
server:
  port: 5000
  
---

# 開発環境（dev）
spring:
  config:
    activate:
      on-profile:
      - dev
  datasource:
    url: jdbc:mysql://aa157c4y3qfjef0.cc2cv1hryoxu.ap-northeast-1.rds.amazonaws.com:3306/ebdb
    username: admin
    password: tanaka3284
  sql:
    init:
      mode: always
      